### ISSUE TITLE
CM4001032 Not Recognized

### ISSUE THREAD

**Issue by SimpleTheory** [adafruit/Adafruit_Python_PlatformDetect#244]
So I am trying to light up an LED strip through my new CM4, with the code:
```
# Simple test for NeoPixels on Raspberry Pi
import time
import board
import neopixel

#The neopixel library requires sudo and if you run sudo from within
#the virtual environment it pulls it out to global and cant grab the right libraries
#Instead use sudo to run the environment's python executable

#sudo ./venv/bin/python3 simpleLEDStrip.py


# Choose an open pin connected to the Data In of the NeoPixel strip, i.e. board.D18
# NeoPixels must be connected to D10, D12, D18 or D21 to work.
PIN_LED_STRIP = board.D12

# The number of NeoPixels
NUM_LEDS = 5

# The order of the pixel colors - RGB or GRB. Some NeoPixels have red and green reversed!
# For RGBW NeoPixels, simply change the ORDER to RGBW or GRBW.
ORDER = neopixel.GRB

pixels = neopixel.NeoPixel(
    PIN_LED_STRIP, NUM_LEDS, brightness=1.0, auto_write=False, pixel_order=ORDER)

#pixels.brightness(.5)

pixels.fill((255,0,0))
pixels.show()
while True:
   print(".")
   time.sleep(1)
```
but I got this error.
```
Traceback (most recent call last):
  File "/home/ari/Documents/rice_algorithm/led.py", line 3, in <module>
    import board
  File "/home/ari/Documents/rice_algorithm/venv/lib/python3.9/site-packages/board.py", line 279, in <module>
    raise NotImplementedError(
NotImplementedError: Adafruit-PlatformDetect version 3.27.2 was unable to identify the board and/or microcontroller running the Linux platform. Please be sure you have the latest packages running: 'pip3 install --upgrade adafruit-blinka adafruit-platformdetect'
```
After some digging around I suspect the issue to be adafruit_platformdetect/constants/board.py on line 492:
```
RASPBERRY_PI_CM4: ("a03140", "b03140", "c03140", "d03140", "d03141"),
```
The reason being when running detect.py I get:
```
Chip id:  BCM2XXX
Board id:  None

Is this a DragonBoard 410c? False
Is this a Pi 3B+? False
Is this a Pi 4B? False
Is this a 40-pin Raspberry Pi? False
Is this a Raspberry Pi Compute Module? False
Is this a BeagleBone Board? False
Is this a Giant Board? False
Is this a Coral Dev Board? False
Is this a Coral Dev Board Mini? False
Is this a MaaXBoard? False
Is this a MaaXBoard Mini? False
Is this a SiFive Unleashed?  False
Is this a PYNQ Board? False
Is this a Rock Pi board? False
Is this a NanoPi board? False
Is this a Khadas VIM3 board? False
Is this a Clockwork Pi board? False
Is this an embedded Linux system? True
Is this a generic Linux PC? False
Is this a UDOO Bolt? False
Is this an ASUS Tinker Board? False
Is this an STM32MP1 Board? False
Is this an OS environment variable special case? False
Raspberry Pi detected.
```
And on cat /proc/cpuinfo I get:
```
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: a03141
Serial		: 100000005724944b
Model		: Raspberry Pi Compute Module 4 Rev 1.1
```
My revision number _**a03141**_ is not on the revision numbers of constants/board.py line 492 for CM4. So I tried hardcoding the number into the file and now on detect.py I get:    _Is this a Raspberry Pi Compute Module? True_

However, even after modding my revision number and trying to run my original program again I still get another error.
```
Traceback (most recent call last):
  File "/home/ari/Documents/rice_algorithm/led.py", line 31, in <module>
    pixels.show()
  File "/home/ari/Documents/rice_algorithm/venv/lib/python3.9/site-packages/adafruit_pixelbuf.py", line 204, in show
    return self._transmit(self._post_brightness_buffer)
  File "/home/ari/Documents/rice_algorithm/venv/lib/python3.9/site-packages/neopixel.py", line 180, in _transmit
    neopixel_write(self.pin, buffer)
  File "/home/ari/Documents/rice_algorithm/venv/lib/python3.9/site-packages/neopixel_write.py", line 38, in neopixel_write
    return _neopixel.neopixel_write(gpio, buf)
  File "/home/ari/Documents/rice_algorithm/venv/lib/python3.9/site-packages/adafruit_blinka/microcontroller/bcm283x/neopixel.py", line 82, in neopixel_write
    raise RuntimeError(
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)
swig/python detected a memory leak of type 'ws2811_t *', no destructor found.
```
So I thought I would report this issue here and in any other relevant repos. If you have any questions or want me to do anything on my end please respond and let me know.

**Comment by makermelissa** [comment]
Yeah, it looks like Raspberry Pi made another revision of boards. Want to submit a PR and add **a03141**, **b03141**, and **c03141**?

As for the second error, it sounds like https://github.com/adafruit/Adafruit_Blinka/issues/532 and https://github.com/adafruit/Adafruit_Blinka/issues/381.
