### ISSUE TITLE
Problem for Orange Pi zeros 2 detection on Debian

### ISSUE THREAD

**Issue by ed-auvinet** [adafruit/Adafruit_Python_PlatformDetect#285]
Hi there,

The detection script had a problem with the detection of the orange pi board.

With the modification of the board.py file at line 612 "orange pi" => "orangepi" all come back to normal.

**Comment by makermelissa** [comment]
Since it's been that way for 2 years without issue, it might be wise to just check for either value to avoid breaking it for others.

**Comment by ed-auvinet** [comment]
Thanks a lot for your feedback.

In the actual version it seems to be "orange pi" and now the board come as
"orangepi".

Best regards

Ed

**Comment by Foxelix** [comment]
Prosím řeším následují problém na mém zařízení Orangepi 3 lts viz. chybové hlášení: Už jsem zkoušel několikrát přeinstalovat a upravit ...bohužel pořád se objevuje stejná chyba : 
orangepi@orangepi3-lts:~$ /bin/python3 "/home/orangepi/Desktop/kontrola knihovny Adafruit_CircuitPython_PCF8574.py"
Traceback (most recent call last):
  File "/home/orangepi/Desktop/kontrola knihovny Adafruit_CircuitPython_PCF8574.py", line 2, in <module>
    import board
  File "/home/orangepi/.local/lib/python3.9/site-packages/board.py", line 351, in <module>
    raise NotImplementedError(
NotImplementedError: 
        Adafruit-PlatformDetect version 3.45.1 was unable to identify the board and/or
        microcontroller running the Linux platform. Please be sure you
        have the latest packages running:
        'pip3 install --upgrade adafruit-blinka adafruit-platformdetect'
Předem děkuji za pomoc a radu jak odstranit

**Comment by makermelissa** [comment]
Could either of you provide some more details such as the OS that you are running. If armbian, I'm surprised https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/main/adafruit_platformdetect/board.py#L359-L360 isn't detecting the Orange Pi Zero 2 and https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/main/adafruit_platformdetect/board.py#L341-L342 isn't detecting the Orange Pi 3 LTS.

If it's a different OS, place respond with the results of `cat /proc/device-tree/model`.

**Comment by Foxelix** [comment]
Sorry I didn't list my OS.
My orange pi 3 lts runs Debian. I tried reinstalling and upgrading several times but it didn't help.
I will try the link to the code you provided to see if I can reinstall board.py

**Comment by kaangoksal** [comment]
@makermelissa 

this is also not detected, I think this is a new batch of raspberry pis

```
(venv) pi@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

(venv) pi@raspberrypi:~ $ cat /proc/device-tree/model
Raspberry Pi 3 Model B Plus Rev 1.4(venv)
```

**Comment by Foxelix** [comment]
Even after installing patch 288, see your link, the problem with determining the SCK and SDA pins persists. Is it possible that changing the operating system would solve the problem? I'm using a whole bunch of libraries installed on my device, but most of the code is giving me an adafruit-blinka problem.
Please help.

**Comment by kaangoksal** [comment]
@Foxelix you can use the pin number instead of board.SDA

Which orange pi is this?

**Comment by Foxelix** [comment]
i have the pi 3 lts version. I've already installed all possible libraries and done the WiringOP config for Orangepi, but I'm still having a problem with accessing the gpio. Also I don't see gpio readall which is weird :(

**Comment by nopnop2002** [comment]
Most board detection problems in the OrangePi series are caused by differences in the OS being used.

>Perhaps a markdown page that lists the OS that the board was tested with may be helpful.

That's exactly right, but I still can't find this.


If you have a markdown list of tested OSes, users can select an OS from that list and avoid board detection issues.

Many users may provide unmarked OS tests and patches.

**Comment by jlsilicon** [comment]
Nice that you SEE the PROBLEM...
Could YOU actually FIX it ... ???

**Comment by jlsilicon** [comment]
Lamo answer.

I use ubuntu.
-I am sure many other developers do too.
