### ISSUE TITLE
Is the new Raspberry Pi CM5 Rev 1.0 board supported?

### ISSUE THREAD

**Issue by Sparqx73** [adafruit/Adafruit_Python_PlatformDetect#373]
I am using the new Raspberry Pi 5 Compute IO Board with a CM5 and I am getting the following error when running a python script to display Raspberry Pi Stats on an Oled which uses the Adafruit Blinka Libraries:

python3 monitor.py
Traceback (most recent call last):
  File "/home/pi/OLED_Stats/monitor.py", line 7, in <module>
    import board
  File "/home/pi/stats_env/lib/python3.11/site-packages/board.py", line 451, in <module>
    raise NotImplementedError(
NotImplementedError: 
        Adafruit-PlatformDetect version 3.75.0 was unable to identify the board and/or
        microcontroller running the Linux platform. Please be sure you
        have the latest packages by running:
        'pip3 install --upgrade adafruit-blinka adafruit-platformdetect'

        If you are running the latest package, your board may not yet be supported. Please
        open a New Issue on GitHub at https://github.com/adafruit/Adafruit_Blinka/issues and
        select New Board Request.

Are you able to advise whether the new Compute Module 5 is supported? Or when it will be supported?

Thanks in advance for your help

**Comment by makermelissa** [comment]
Fixed via #374
