### ISSUE TITLE
Error on detector due to new implementations

### ISSUE THREAD

**Issue by yeyeto2788** [adafruit/Adafruit_Python_PlatformDetect#50]
Using the `detect.py` and exception is raised due to new implementations (Onion Omega implementations)

 ```console
Traceback (most recent call last):
  File "/home/xxx/own_workspace/Adafruit_Python_PlatformDetect/bin/detect.py", line 7, in <module>
    print("Chip id: ", detector.chip.id)
  File "/home/xxx/own_workspace/Adafruit_Python_PlatformDetect/adafruit_platformdetect/chip.py", line 66, in id
    return self._linux_id()
  File "/home/xxx/own_workspace/Adafruit_Python_PlatformDetect/adafruit_platformdetect/chip.py", line 111, in _linux_id
    if "MIPS 24Kc" in cpu_model:
TypeError: argument of type 'NoneType' is not iterable
```
I'll file a PR fixing the issue.

**Comment by yeyeto2788** [comment]
My bad, the issue was already fixed. Sorry for the mistake.
